minimalLabelSize = true
deleteBoxesOnDisable = true
sendBoxes = false
showBoxesWhenDisabled = true
backgroundForLabels = true
incrementColor = false
innerDiagonal = true
showOtherUsersBoxes = true
colorIndex = 15
